# Generated by Django 3.1.5 on 2021-08-05 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(max_length=128)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.category')),
            ],
        ),
    ]
